name: Archive

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/45 * * * *"
  workflow_dispatch:

# parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r source/python-application/requirements.txt

    - name: Make files
      run: |
        python3 --version
        python3 source/python-application/generation.py

    - name: Change old files to new
      run: |
        git config --global user.name "fortarchive[bot]"
        git config --global user.email "webfortcf@gmail.com"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m '${{ env.version_build }}' || echo
        git push
